device: 0
cpu_num: 48

image_size: [640, 640]

out_path: runs
exist_ok: False

lucky_number: 10
use_wandb: False
use_tensorboard: True

weight: True # Path to weight or True for auto, False for no pretrained weight
